### ISSUE TITLE
Support abandoning statements

### ISSUE THREAD

**Issue by abingham** [sixty-north/gjenta#1]
We need to be able to abandon statements, e.g.::

```
x = {
   '1': 2,
```

I'm imagining something like:

```
x = {
    1: 2,
    #;; abandon
```

**Comment by abingham** [comment]
We added support for control characters in the wrapper. So now you can say things like:
```
x = {
    1: 2,
^C
```
And a control-C will be passed naturally to the underlying REPL process. This seems to work.

Note that you can also do things like pass control-D to the REPL, killing it. This is probably not what you want to do, but you can do it if you want.

**Comment by abingham** [comment]
This is not entirely solved. We're currently printing the "^C" to the output where it shouldn't be. We need to strip this from the output.

**Comment by abingham** [comment]
This should be fixed in 2082d33d0e6b394636068a39ebe95c7df7801b79

**Comment by rob-smallshire** [comment]
So this crosses the rubicon into the file being invalid Python, does it not?

**Comment by abingham** [comment]
Yes, as currently implemented. I thought it was much more readable than some comment-based alternative.

**Comment by rob-smallshire** [comment]
Oh I agree, it is.
