### ISSUE TITLE
Timing of newline

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/gjenta#13]
Consider this, from `examples/commands.py`:

```
#;; command wait-until 0 0 17
#;; result wait-until 0 0 20
x
```

If you run this is the terminal, you'll notice that the cursor moves to the next line too early, giving the impression that Return has been pressed, before the result timeout is reached. This gives the mistaken impression that the command is taking a long time to run, rather than there being a delay after the command has been entered, but before it it executed.

We need to not send the newline at the end of a command until the right moment.

**Comment by abingham** [comment]
This should be fixed in 98d7826e35c0083c6c9ba2decb3c5c9c34533374.  Give it a try, and close this out if it works for you.
